### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by jdouglas2005** [JoshuaMaiorino/Open-Connections-Digest#3]
I'm not a programmer, but the first time this job tried to run, I got this message:

Last Status Message: Method not found: 'System.Collections.Generic.IEnumerable`1 Rock.Model.GroupServiceExtensions.ActiveMembers(Rock.Model.Group)'.

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1 Rock.Model.GroupServiceExtensions.ActiveMembers(Rock.Model.Group)'. at org.ourcitychurch.Jobs.ConnectionRequestEmailDigest.Execute(IJobExecutionContext context) at Quartz.Core.JobRunShell.Run() --- End of inner exception stack trace --- [See nested exception: System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1 Rock.Model.GroupServiceExtensions.ActiveMembers(Rock.Model.Group)'. at org.ourcitychurch.Jobs.ConnectionRequestEmailDigest.Execute(IJobExecutionContext context) at Quartz.Core.JobRunShell.Run()]

Can someone point me in the right direction for a solution to this?  Am I missing something for the setup?

**Comment by cbump** [comment]
Hey @jdouglas2005 what version of Rock are you running?

**Comment by jdouglas2005** [comment]
7.4 and will be updating to 7.5 soon.

On Oct 2, 2018, at 8:57 AM, Chuck Bump <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @jdouglas2005<https://github.com/jdouglas2005> what version of Rock are you running?

**Comment by cbump** [comment]
You tested this plugin on 1.7.4?  The Rock.Model.GroupServiceExtensions.ActiveMembers method was added in version 1.7.4 so you shouldn't see this error on anything 7.4 or greater . . .  Thanks!

Chuck Bump

**Comment by jdouglas2005** [comment]
Correct.

On Oct 2, 2018, at 12:09 PM, Chuck Bump <notifications@github.com<mailto:notifications@github.com>> wrote:


You tested this plugin on 1.7.4? The Rock.Model.GroupServiceExtensions.ActiveMembers method was added in version 1.7.4 so you shouldn't see this error on anything 7.4 or greater . . . Thanks!

Chuck Bump

**Comment by cbump** [comment]
Can you test it on 7.5 once you upgrade and let us know if it's still giving the same error please?

**Comment by jdouglas2005** [comment]
I sure will.

On Oct 2, 2018, at 12:17 PM, Chuck Bump <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you test it on 7.5 once you upgrade and let us know if it's still giving the same error please?

**Comment by jdouglas2005** [comment]
I tested it on 7.5 and got did not get the error message. ☺  However, 0 emails were delivered because I have no one listed in the standard “Connector Group.”  Our Connector Groups are actually spread out in various places because we are pulling from our staff structure predominately and from serving teams secondarily.  It seems the job settings only allow one group to be selected as individuals who will receive the digest…is there a way I can select multiple groups – or tell it to send to anyone assigned as a connector regardless of the group they belong to?

JAKE DOUGLAS
MINISTRY ANALYST
VALLEY REAL LIFE

1831 S. BARKER RD., GREENACRES, WA 99016
P: 509.232.0840    F: 509.232.0848     W: WWW.VRL.CHURCH<http://www.valleyreallife.org/>
SERVICE TIMES: THURSDAYS @ 6:30PM & SUNDAYS @ 8, 9:30 & 11:00AM

**Comment by JoshuaMaiorino** [comment]
This plugin is now managed by Bema.  You can post issues here:
https://github.com/BEMADEV/Rock/issues
Sorry for the late response.  I haven't been tracking this repo.
